# Generated by Django 3.0.7 on 2023-02-04 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido_1', models.CharField(max_length=255)),
                ('apellido_2', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_ingreso', models.DateField(auto_now=True)),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.Cliente')),
                ('id_equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido_1', models.CharField(max_length=255)),
                ('apellido_2', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repuesto', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=100)),
                ('stock', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido_1', models.CharField(max_length=255)),
                ('apellido_2', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('id_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.Area')),
            ],
        ),
        migrations.CreateModel(
            name='tecnicoRepara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_inicio', models.DateField(auto_now=True)),
                ('f_final', models.DateField(null=True)),
                ('idTecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.Tecnico')),
                ('id_ingreso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.Ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=255)),
                ('id_marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.Marca')),
            ],
        ),
        migrations.AddField(
            model_name='ingreso',
            name='id_recepcionista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.Recepcionista'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='id_modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.Modelo'),
        ),
        migrations.CreateModel(
            name='detalleReparacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=100)),
                ('id_reparacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.tecnicoRepara')),
                ('id_repuesto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.Repuesto')),
            ],
        ),
    ]
